# Generated by Django 2.1.2 on 2018-10-20 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyclicSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Time')),
                ('water_amount', models.IntegerField(verbose_name='Water amount')),
            ],
            options={
                'verbose_name': 'Cyclic schedule',
                'verbose_name_plural': 'Cyclic schedules',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, verbose_name='Type')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
            },
        ),
        migrations.CreateModel(
            name='ScheduledWatering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('scheduled_watering_date', models.DateTimeField(verbose_name='Scheduled watering date')),
                ('watering_performed_date', models.DateTimeField(null=True, verbose_name='Watering performed date')),
                ('cyclicSchedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='centralunit.CyclicSchedule', verbose_name='Cyclic Schedule')),
            ],
            options={
                'verbose_name': 'Scheduled watering',
                'verbose_name_plural': 'Scheduled waterings',
            },
        ),
        migrations.CreateModel(
            name='SensorUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Sensor unit',
                'verbose_name_plural': 'Sensor units',
            },
        ),
        migrations.CreateModel(
            name='WaterUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Water unit',
                'verbose_name_plural': 'Water units',
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor_unit',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.DO_NOTHING, to='centralunit.SensorUnit', verbose_name='Sensor unit'),
        ),
        migrations.AddField(
            model_name='cyclicschedule',
            name='water_unit',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.DO_NOTHING, to='centralunit.WaterUnit', verbose_name='Water unit'),
        ),
    ]
